#%RAML 1.0 NamedExample
value:
  -
    StudentID: 7897
    Student Name: "Addis G"
    Student Status: Active
    Student Grade: "12B"
  -
    StudentID: 9056
    Student Name: "Helen B"
    Student Status: Active
    Student Grade: "12A"